CREATE TABLE Favorites (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           userid VARCHAR(255),
                           trackid VARCHAR(255)
);
